### ISSUE TITLE
Create a list with audio files with searching recursively user's home directory

### ISSUE THREAD

**Issue by vaslabs** [vaslabs/pi-web-agent#101]
Additional functionality for mplayer

**Comment by agalazis** [comment]
already here  we justin to create the playlist ui in the next iteration:
https://gist.github.com/agalazis/25478eb1c67d5378f0d2

**Comment by agalazis** [comment]
closing so that nobody else works on this. we just need the playlist ui scheduled for the next iteration

**Comment by vaslabs** [comment]
Never close an issue that has not been resolved
