### ISSUE TITLE
Optional split window to display or edit the commands and configuration on the command line

### ISSUE THREAD

**Issue by siladu** [vaslabs/pi-web-agent#103]
I recently read the Linux Journal article about pi-web-agent and it mentions one of the decisions for choosing Raspberry Pi was for educational purposes.

I think a nice educational feature would be to see what commands are being run and how the configuration files are being changed as you use the GUI configuration.
Perhaps even better would be a split window that updates in real time but also with live editing capability so the user can switch between making changes using the GUI or using the command line.

An essential minimum requirement for this feature would be a console view that displays the commands being run as you use the GUI.
An improvement could be to filter out anything that was irrelevant (e.g. 'cd's or trivial file management).
An even further improvement would be making that console an editable live terminal session. 

For configuration files specifically, perhaps a diff view of the change just made in the GUI?
If one GUI action results in multiple commands and/or multiple configuration files being changed then this could be quite a tricky display issue.

**Comment by vaslabs** [comment]
pi-web-agent UI should be command line free. Command line is easily accessible from an ssh client
