### ISSUE TITLE
Migrate update module to new standard

### ISSUE THREAD

**Issue by vaslabs** [vaslabs/pi-web-agent#112]

**Comment by azardilis** [comment]
Done in last pull req. Pretty much just a refactor of the python code into 'update.py' for serving the static page and 'update_api.py' for doing the update work. Only thing moved completely are the dynamic html string building stuff which are now in 'css/update.js'.
Closing for now, but pull and let me know if there are any problems

**Comment by vaslabs** [comment]
Awesome!!! Thanks.
