### ISSUE TITLE
Get rid of BlueprintDesigner.py and HTMLPageGenerator, move output methods to the core.

### ISSUE THREAD

**Issue by vaslabs** [vaslabs/pi-web-agent#113]

**Comment by agalazis** [comment]
I removed   Got rid of BlueprintDesigner.py and HTMLPageGenerator but I am not sure about the output in framework and in chrome/view

**Comment by agalazis** [comment]
the framework  one is the one that is actually used but let me know what are your plans about it.

**Comment by vaslabs** [comment]
Compose json, compose html etc are needed, move them to the framework module before deleting html page generator otherwise everything will break

**Comment by agalazis** [comment]
a ok it was late so I didn't check that, I figured out this morning xD

**Comment by agalazis** [comment]
moved to view to avoid  circuar imports(framework imports view which needs the outout functions ) View seems to be th information expert for output anw
