### ISSUE TITLE
Tool to construct packages for the various supported distros

### ISSUE THREAD

**Issue by vaslabs** [vaslabs/pi-web-agent#117]

**Comment by agalazis** [comment]
Is there any similar tool ? One idea is to have different folders with the installation slit into parts eg:
install
|_pidori/websocketdBro
|_rspbian/websocketdBro

then in the script
DSITRO = $(determinedistro)
and when we want to install we will use:
./install/$DSITRO/websocketdBro        #or even define functions for each component

**Comment by vaslabs** [comment]
We want rpm and deb packages that will have all the information including dependencies

**Comment by agalazis** [comment]
I suggest closing this issue the purpose  of the other issues is to make the scripts for building   the suggested packages(not just building manually once)

**Comment by vaslabs** [comment]
Didn't quite get that...

**Comment by vaslabs** [comment]
This issue is an epic, it considers all packaging related issues. Of this was jira, every related issue would be linked to this epic
