### ISSUE TITLE
rename css folder to assets

### ISSUE THREAD

**Issue by agalazis** [vaslabs/pi-web-agent#119]
The assets folder should contain subfolders for each application. The system- wide assets should be located to assets/system and 3d party libraries (not specific to each application) should also be added there

eg. the folder stracture could be like this:
assets/
|_____/system
...........|_____css
...........|_____js
|_____/mplayer
...........|_____css
...........|_____js
|_____/filemanager
...........|_____css
...........|_____js

 What do you think?

**Comment by vaslabs** [comment]
It's a brilliant idea, better than the current structure anyway.
