### ISSUE TITLE
Some users complaint about the rabbit mq. Make installation of mplayer dependencies optional.

### ISSUE THREAD

**Issue by vaslabs** [vaslabs/pi-web-agent#131]
This is quite urgent

**Comment by agalazis** [comment]
Ok

**Comment by agalazis** [comment]
My sincerest apologies about rabbitMQ,what was the problem the philosophy behind making it a system-wide dependency is than any application can use it's own channel. If we have a system wide dependency  we won't end up having different flavors of message ques in every application. Ofcourse am not sure what is the exact problem they refer to... but a quick solution is to make it optional

**Comment by agalazis** [comment]
I believe that there is no problem to remove it as any application that will use it can have it as a depndency as well

**Comment by vaslabs** [comment]
This issue will be closed because the users that complaint didn't give enough information and no other complaints have been filed.
