### ISSUE TITLE
IndieCity dead -- how to install?

### ISSUE THREAD

**Issue by stuzog** [vaslabs/pi-web-agent#136]
With IndieCity now dead, how can pi-web-agent be installed on a Pi?

**Comment by vaslabs** [comment]
https://github.com/vaslabs/pi-web-agent/releases

**Comment by stuzog** [comment]
Thanks, Vasilis!

Vasilis Nicolaou wrote:

**Comment by stuzog** [comment]
Unfortunately, it stil doesn't work. After installation, I get:

$ sudo /etc/init.d/pi-web-agent start
Starting pi web agent [ FAILED ]

Following the instructions, the directory structure set up in / is:



Is this correct?

Stuart

**Comment by vaslabs** [comment]
can you do an ls on your current directory that you are running ./install.sh and paste what you get here?

**Comment by vaslabs** [comment]
Also could you send me the error logs that are in /var/log/pi-web-agent

**Comment by stuzog** [comment]
pi@raspberrypi /pi-web-agent0.4.2/0.4.2 $ ls
AUTHORS   etc         LICENSE  run.sh        setup_dev.sh  uninstall.sh
build.sh  install.sh  README   setup_common  setup.sh      usr

Stuart

**Comment by vaslabs** [comment]
that looks alright, send me the error log in /var/log/pi-web-agent to see where the apache failed

**Comment by stuzog** [comment]
Hi Vasilis,

There is no error log, just service.log:

pi@raspberrypi /var/log/pi-web-agent $ ls
service.log
pi@raspberrypi /var/log/pi-web-agent $ cat service.log
apache2: Syntax error on line 106 of 
/etc/pi-web-agent/conf/apache2-appliance.conf: Cannot load 
modules/mod_authn_alias.so into server: 
/etc/pi-web-agent/modules/mod_authn_alias.so: cannot open shared object 
file: No such file or directory

Stuart

Vasilis Nicolaou wrote:

**Comment by vaslabs** [comment]
oh dear, it looks like apache got updated.
We haven't worked on pi-web-agent for a long time...
I guess the solution would be to open /etc/pi-web-agent/conf/apache2-appliance.conf and comment out the modules that are not used but I think there will be problems with some keywords as well.

**Comment by vaslabs** [comment]
or downgrade to apache 2.2

**Comment by stuzog** [comment]
Unfortunately, that's beyond my ability right now, I'm new to Linux.

S.

Vasilis Nicolaou wrote:

**Comment by vaslabs** [comment]
ah, sorry mate. I hope I'll find some time to find a fix but I'm struggling with other projects.

**Comment by stuzog** [comment]
OK, I understand. It's not mission-critical for me.
Thanks for your help and especially for your quick response,
All the best,
Stuart

Vasilis Nicolaou wrote:

**Comment by vaslabs** [comment]
Out of interest, I know the apache config is not working with ubuntu. What distro have you installed?

**Comment by stuzog** [comment]
Raspbian Jesse (Debian 8.0)

Vasilis Nicolaou wrote:

**Comment by vaslabs** [comment]
Thanks. I'll install it when I have time and make a fix

**Comment by agalazis** [comment]
well I was thinking to make a release on 1st feb 
We can put all our efforts to improve install process first

**Comment by vaslabs** [comment]
Yes, if you can write some guidelines how we use what's in the current master branch, then we'll all be at the same page

**Comment by stuzog** [comment]
Hi Vasilis,

I'm not quite sure what you mean, but I installed in the pi user 
directory as per the link in your email. It started with:

pi@raspi ~/pi-web-agent0.4.2/0.4.2 $ sudo ./install.sh
Installing pi web agent [ OK ]
initialising submodules ...
fatal: Not a git repository (or any of the parent directories): .git
[ OK ]
Updating packages
....[etc]

It seemed to install everything:
All Done.

NOTE: To compile programs with wiringPi, you need to add:
-lwiringPi
to your compile line(s) To use the Gertboard, MaxDetect, etc.
code (the devLib), you need to also add:
-lwiringPiDev
to your compile line(s).

DONE

But ended with:

Registering pi-web-agent in sudoers
Starting pi-web-agent
Starting pi web agent [ FAILED ]
/home/pi/pi-web-agent0.4.2/0.4.2
pi@raspi

Also:

pi@raspi ~ $ sudo /etc/init.d/pi-web-agent start
Starting pi web agent [ FAILED ]

Stuart

Vasilis Nicolaou wrote:

**Comment by vaslabs** [comment]
Hi,
Sorry, my response was for @agalazis . you don't need to do anything else, once we fix it this ticket will be closed. But it will take a while since everyone seems busy.

**Comment by vaslabs** [comment]
Hello @stuzog .
I'm happy to let you know that I've just released pi-web-agent for raspbian jessie
https://github.com/vaslabs/pi-web-agent/releases/tag/0.4-rc-2_jessie
Let me know for any issues.
