### ISSUE TITLE
Responsive UI

### ISSUE THREAD

**Issue by vaslabs** [vaslabs/pi-web-agent#141]
I'm initially assigning it to you @agalazis . We should completely redesign the UI.

**Comment by agalazis** [comment]
True that I thought of it before although even at work I am using backbone at a widget level. I think it would be nice to move on with webcomponents on this project but we 'll need to create something clever that every developer can work with independently of their background.The main issue is re-usability of ui components + organizing/building/ optimizing custom ui code . With the current problems responsive ui becomes a secondary issue, but we can have it in mind while we rebuild ui development process

**Comment by vaslabs** [comment]
no, first lets redesign the UI to be responsive. Remove bootstrap and put foundation3 instead, I like more the class names. We can also use material design. Forget about plugins for now, although we should be able to separate js from css.

**Comment by vaslabs** [comment]
maybe webcomponents is a good idea

**Comment by vaslabs** [comment]
branch : https://github.com/vaslabs/pi-web-agent/tree/materializeDesign
